# Learn more at https://jupyterbook.org/customize/config.html

# Book settings
title: TEXTILE (Tutorials for Experimentalist Interactive Learning)
author: Hawley Helmbrecht, Elizabeth Nance
# logo: img/logos/logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Launch button settings
launch_buttons:
  binderhub_url : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  colab_url : https://colab.research.google.com # The URL of Google Colab (https://colab.research.google.com)

# Information about where the book exists on the web
repository:
  url: https://github.com/tengjuilin/textile  # Online location of your book
  branch: master

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  use_multitoc_numbering: false  # reset TOC between parts